version: '3.5'

services:

  mysql:
    container_name: 'swg_go_mysql'
    image: mysql:5.7    
    environment:      
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'      
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3399
    ports:
      - 3399:3399
    expose:
      - '3399'
    volumes:    
      - ./mysql:/docker-entrypoint-initdb.d/
      - mysql:/var/lib/mysql
    networks:
      - network      
    
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5   
          

networks:  
  network:
    name:   swg_go_network
    driver: bridge

volumes:
  mysql:
    name: swg_go_mysql

    
     
 