basePath: /
definitions:
  auth.LoginDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  user.UserDto:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
host: localhost:5050
info:
  contact: {}
  description: Implement swagger-ui on Go project with Gorilla Mux (web framework)
    + JWT Authorization
  license: {}
  title: Demo Swagger-UI (GO+GORILLA MUX) for Nexsoft Project
paths:
  /v1/auth/login:
    post:
      description: Get JWT token for access all APIs
      parameters:
      - description: LoginDto.go
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/auth.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: Response Success (UserDto.go)
          schema:
            $ref: '#/definitions/user.UserDto'
      summary: login
      tags:
      - auth
  /v1/user/delete/{id}:
    delete:
      description: delete
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Response Success (UserDto.go)
          schema:
            $ref: '#/definitions/user.UserDto'
      summary: delete
      tags:
      - user
  /v1/user/list:
    get:
      description: list
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response Success (UserDto.go)
          schema:
            $ref: '#/definitions/user.UserDto'
      summary: list
      tags:
      - user
  /v1/user/save:
    post:
      description: save
      parameters:
      - description: UserDto.go
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/user.UserDto'
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response Success (UserDto.go)
          schema:
            $ref: '#/definitions/user.UserDto'
      summary: save
      tags:
      - user
  /v1/user/update/{id}:
    put:
      description: update
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: UserDto.go
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/user.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: Response Success (UserDto.go)
          schema:
            $ref: '#/definitions/user.UserDto'
      summary: update
      tags:
      - user
  /v1/user/view/{id}:
    get:
      description: view
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Response Success (UserDto.go)
          schema:
            $ref: '#/definitions/user.UserDto'
      summary: view
      tags:
      - user
schemes:
- http
securityDefinitions:
  Authorization:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
